<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{b30f7bc4-5585-48ba-bc0b-09674d757870}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	a:INT;
	b:INT;
	c:INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[c:=a+b;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>